FROM nvidia/cuda:11.1.1-devel-ubuntu20.04
#FROM ubuntu:20.04

LABEL "description"="MAT"

#ARG DEBIAN_FRONTEND=noninteractive
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Istanbul

ENV LANG "en_US.UTF-8"
#RUN locale-gen en_US.UTF-8

RUN dpkg --configure -a
RUN chmod 1777 /tmp
RUN apt-get -y update && apt-get install ffmpeg libsm6 libxext6 -y
RUN apt-get -y install python3-pip
RUN apt-get -y install nano 

COPY . /mat/
WORKDIR /mat/

RUN pip3 install easydict
#RUN pip3 install torch==1.9.1+cu111 torchvision==0.10.1+cu111 torchaudio==0.9.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install matplotlib
RUN pip3 install numpy
RUN pip3 install future
RUN pip3 install opencv-python
RUN pip3 install scikit-image
RUN pip3 install scipy
RUN pip3 install click==8.0.1
RUN pip3 install requests
RUN pip3 install tqdm
RUN pip3 install pyspng
RUN pip3 install ninja
RUN pip3 install imageio-ffmpeg==0.4.3
RUN pip3 install timm
RUN pip3 install psutil
RUN pip3 install scikit-learn

CMD ["sleep", "infinity"]
